version: '3.8'

services:
  db:
    image: postgres:13
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: patricksantos
      POSTGRES_PASSWORD: nova_senha
      POSTGRES_DB: desafio_maino_patrick_development
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -b '0.0.0.0'"
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    environment:
      DATABASE_URL: postgres://patricksantos:nova_senha@db:5432/desafio_maino_patrick_development
      REDIS_URL: redis://redis:6379/1
      RAILS_ENV: production
      SECRET_KEY_BASE: afeda04e5f4d4559ae9064ca72e3148054239033c7d9c8e9c9e46a309ef862380f7942bcacba711659a9800a0c88dc3b85ca79049925773742e84a52fae5f414
    env_file:
      - .env

  worker:
    build: .
    command: bundle exec sidekiq
    volumes:
      - .:/myapp
    depends_on:
      - db
      - redis
    environment:
      DATABASE_URL: postgres://patricksantos:nova_senha@db:5432/desafio_maino_patrick_development
      REDIS_URL: redis://redis:6379/1
      RAILS_ENV: production
      SECRET_KEY_BASE: afeda04e5f4d4559ae9064ca72e3148054239033c7d9c8e9c9e46a309ef862380f7942bcacba711659a9800a0c88dc3b85ca79049925773742e84a52fae5f414
    env_file:
      - .env
